### PR TITLE
docs update

### PR DESCRIPTION
**Pull request by cortner**
I'd like to bring the docs up to date before tagging 0.2. Any help would be appreciated. 

@DexuanZhou  -- it seems the really nice spherical harmonics docs you wrote don't render correctly. Would you mind looking into that? 

To view docs locally 
- go to `Polynomials4ML/docs`
- `julia --project=.` => `] up` => exit repl
- `julia --project=. make.jl`
- the docs pages should now be available under `docs/build`

### CODE REVIEW

**Comment by cortner** [comment]
- [ ] write brief description of ACE layers
- [ ] should we document use of `Dual` and `HyperDual` compatibility? 
- [ ] should we provide a few simple tutorials, see `ACE1pack.jl` for examples?
- [ ] remove `Experimental.md` entirely from the docs? we can keep the md file.

**Comment by DexuanZhou** [comment]
> I'd like to bring the docs up to date before tagging 0.2. Any help would be appreciated.
> 
> @DexuanZhou -- it seems the really nice spherical harmonics docs you wrote don't render correctly. Would you mind looking into that?
> 
> To view docs locally
> 
>     * go to `Polynomials4ML/docs`
> 
>     * `julia --project=.` => `] up` => exit repl
> 
>     * `julia --project=. make.jl`
> 
>     * the docs pages should now be available under `docs/build`



> I'd like to bring the docs up to date before tagging 0.2. Any help would be appreciated.
> 
> @DexuanZhou -- it seems the really nice spherical harmonics docs you wrote don't render correctly. Would you mind looking into that?
> 
> To view docs locally
> 
>     * go to `Polynomials4ML/docs`
> 
>     * `julia --project=.` => `] up` => exit repl
> 
>     * `julia --project=. make.jl`
> 
>     * the docs pages should now be available under `docs/build`

**Comment by DexuanZhou** [comment]
Sorry, I originally wanted to comment 'Sure, I'll look at it right away,' but I accidentally closed the pull request.

**Comment by cortner** [comment]
Hi @CheukHinHoJerry and @DexuanZhou  -- I just accidentally force-pushed an update. Did either of you push to this branch? If you did please keep your local copy so you can apply this again. sorry If I created a mess.

**Comment by cortner** [comment]
@DexuanZhou  -- lookup the `Documenter.jl` documentation to see how to write Latex in Documenter. 

Both -- checkout the first Literate.jl tutorial I wrote. I'd like to add a few more. Let me know if you have suggestions.

**Comment by cortner** [comment]
@DexuanZhou  -- I found your commit that I accidentally overwrote: 

https://github.com/ACEsuit/Polynomials4ML.jl/commit/8f0f245b9d82c4bd563aea5b399e92a38b18cda4

If you still have the corrected file, can you please commit it again? If not I will try to recover this tomorrow.

**Comment by CheukHinHoJerry** [comment]
Sorry I didn't notice there was an update... I will recover what it should be like tonight. Please don't worry about that.

**Comment by cortner** [comment]
yes! all good, I'm glad, thanks for pointing it out.

**Comment by cortner** [comment]
some links are broken, but otherwise I think this is ok-ish. Not great, but a start.

**Comment by cortner** [comment]
@DexuanZhou  and @CheukHinHoJerry  -- I think this is more or less ready. I'd be greatful if you can take another look and let me know if you think anything is missing or not working as expected.

**Comment by CheukHinHoJerry** [comment]
Some links in SH.md is not working and I fixed it. 

Another thing is that I cannot find `SparseSymprod` and `PooledSparseProduct` in docstrings, is this on purpose?

**Comment by cortner** [comment]
hm - one last thing we should consider is updating the readme.

**Comment by cortner** [comment]
> Another thing is that I cannot find SparseSymprod and PooledSparseProduct in docstrings, is this on purpose?

THey should be - works for me locally.

**Comment by cortner** [comment]
There are still some broken links but I am getting tired of trying to figure out Documenter. It's not too big a deal. I'm happy to merge and register this as 0.2.0 if @CheukHinHoJerry and @DexuanZhou agree?

**Comment by CheukHinHoJerry** [comment]
No problem from my end.

**Comment by cortner** [comment]
Thank you both

**Pull request merged**
