### PR TITLE
WIP: CachedArray in Linear layer and migrating to `unwrap` from `parent`

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
Idea is to release the input (possibly cached array) with something like this:

```julia
(l::LinearLayer{false})(x::AbstractMatrix, ps, st) = begin
   out = acquire!(st.pool, :bA, (size(x, 1), l.out_dim), eltype(x)); 
   mul!(out, parent(x), transpose(ps.W)); release!(x);
   return out, st
end
```
It also acquire a `CachedArray` that can be released later on. We also have the `use_cache` option as in `PolyLuxLayer` for the user to determined whether to use `tmp` or `cache`.

### CODE REVIEW

**Comment by cortner** [comment]
what's the status of this PR?

**Comment by CheukHinHoJerry** [comment]
I think this is basically done. I just want to finalise it after we have the `unwrap` function in `ObjectPools.jl` since D told he had some problem with the `Adjoint`. Please give me some extra hours tonight to finish it off.

**Comment by cortner** [comment]
Then you can take care of #59 at the same time?

**Comment by CheukHinHoJerry** [comment]
Yes - thank you for raising that. I will take care of that too.

**Comment by CheukHinHoJerry** [comment]
hmm - not sure why only the `TmpArray` interface CI test on julia nightly is failing and it even output warning from deprecating `parent` from tests of `LinearLayer`. Otherwise I think it should be ready to merge. Will take a look later today.

**Comment by CheukHinHoJerry** [comment]
Not sure why still - @cortner could you please take a look when you have time?

**Comment by cortner** [comment]
will try now.

**Comment by cortner** [comment]
odd - everything passes for 1.10-alpha1 on my machine i.e. I can't reproduce it locally. This basically means I don't want to waste our time on it :)

**Comment by cortner** [comment]
@CheukHinHoJerry  -- I've tested, reviewed and am ready to merge it. Are you comfortable for me to register this as a batch release since it only changes the internals but not the interface? But if you strongly prefer we can treat it as breaking.

**Comment by CheukHinHoJerry** [comment]
Yes I think a batch release is good enough. Thank you.

**Comment by cortner** [comment]
@CheukHinHoJerry  -- I can now repduce those warnings on J1.10-beta1, but they are gone on nightly. So probably an intermediate bug. I'll have to explore this a bit more before merging and registering.

**Comment by CheukHinHoJerry** [comment]
Sure - thanks a lot. I think this is a bug from ObjectPools.jl since I failed the test locally from there as I mentioned to you last time.

**Comment by cortner** [comment]
thanks, I'll test this. Will also test on the latest backport 1.10 branch

**Comment by cortner** [comment]
I actually cannot reproduce any failures on any version of 1.9.x and I wonder whether there is any point losing sleep over this in an unreleased version of Julia. Could be a bug in Pkg for all we know.

**Comment by CheukHinHoJerry** [comment]
I only get error in ObjectPools.jl when I run ‘]test’ but it works fine when I run the script directly. Maybe that also implies it is a problem of Pkg?

Given that the CI of stable release J1.8 and J1.9 both pass stably, I have no problem if you prefer merging that.

**Comment by cortner** [comment]
I found the issue: 
```julia
in_d = 10; out_d = 5; N = 7
l = P4ML.LinearLayer(in_d, out_d; feature_first = false)
ps, st = LuxCore.setup(MersenneTwister(1234), l)
X1 = randn(N, in_d)
Y1_ = [ l(X1[i, :], ps, st)[1] for i = 1:N ]
hcat(Y1_...)
```

It appears that `hcat` now calls `parent` whereas before it did not.

**Comment by cortner** [comment]
I don't think this is a bug from our end but it is fortuitious that we are changing to `unwrap` so we avoid this completely. 

My suggestion : even though we did document the `parent` usage in P4ML, it was only for the first 0.3.0 release. Let's hold our nose for five minutes to do the following: 
- remove the deprecation warning from ObjectPools and possibly also remove the `parent` implementation (if that doesn't break the use of CachedArrays)
- then P4ML should work as expected and we can register the next version.

Are you happy with that? I think it is a very small violation of semver and we have no users of the latest versions of ObjectPools and P4ML yet so it should be minimally disruptive IF AT ALL

**Comment by cortner** [comment]
> I only get error in ObjectPools.jl when I run ‘]test’ but it works fine when I run the script directly. Maybe that also implies it is a problem of Pkg?

I still can't reproduce that. Can you open a separate issue in Objectpools with more details?

**Comment by CheukHinHoJerry** [comment]
> I still can't reproduce that. Can you open a separate issue in Objectpools with more details?

Yes, I will do that now. Also I am happy with what you suggest. Removing `parent` should be fine (I think).

**Comment by CheukHinHoJerry** [comment]
> > I only get error in ObjectPools.jl when I run ‘]test’ but it works fine when I run the script directly. Maybe that also implies it is a problem of Pkg?
> 
> I still can't reproduce that. Can you open a separate issue in Objectpools with more details?

I tried that with J1.9.2 and it works fine but it is broken on J.1.9.0. Maybe we can just keep that in mind? I don't think it is the problem from our end.

**Comment by cortner** [comment]
actually please don't do it yet. I had another idea.

**Comment by cortner** [comment]
here is what I added - will register Objectpools 0.3.1 in a moment: 
```julia
# for some reason @deprecate doesn't work here. Getting 
# error messages we don't understand. This here will do until 
# we tag the next version. 
# In Julia 1.10-beta1 it seems that `parent` is used in ways we didn't 
# expect, causing warnings all over the place, hence we keep this only for 
# older versions of Julia. 
if VERSION < v"1.10-"
   function Base.parent(pA::FlexCachedArray)
      @warn("Use of `parent` to obtain the PtrArray of a FlexCachedArray is deprecated. Use `unwrap` instead.")
      return unwrap(pA)
   end
end 
```

**Comment by cortner** [comment]
Once the new ObjectPools is registered I will add a version bound here, test, merge and register.

**Comment by CheukHinHoJerry** [comment]
Thank you for your help - much messier than I expected.

**Pull request merged**
