### PR TITLE
rnl+rlm basis

### PR DESCRIPTION
**Pull request by DexuanZhou**
src/atomicorbitalsradials: AtomicOrbitalsRadials, GaussianBasis, SlaterBasis, STO_NG 

src/sphericalharmonics/rlm: 
crlm.jl: complex spherical harmonics + solid harmonics
rrlm.jl: real spherical harmonics+ solid harmonics

### CODE REVIEW

**Comment by cortner** [comment]
Hi @DexuanZhou  -- let me know please if you want help rebasing this PR onto `v0.1.0-dev`?

**Comment by cortner** [comment]
looks like you managed fine :)

**Comment by cortner** [comment]
Note that @CheukHinHoJerry put the product basis into `v0.1.0-dev` -- you could use this to rewrite the AtomicOrbitals, but you don't have to, it's also ok to just stick with what you have for now.

**Comment by cortner** [comment]
Hi Dexuan - I see you are editing the docs. THANK YOU!! 

If you want to build them locally on your machine to look at use this, starting from `./doc/` 
* Open `julia --project=..`, package manager `]` then `up`, then `dev ..`; this will make sure the package version you are building the docs for is the one you are working on. Please make sure to *NOT* commit the Manifest that this creates! 
* Then exit julia again and from the terminal run `julia --project=.. make.jl` ; this should build the docs 
* open `./docs/build/index.html`

**Comment by DexuanZhou** [comment]
> Note that @CheukHinHoJerry put the product basis into `v0.1.0-dev` -- you could use this to rewrite the AtomicOrbitals, but you don't have to, it's also ok to just stick with what you have for now.

I'll look at that.

**Comment by DexuanZhou** [comment]
> Hi Dexuan - I see you are editing the docs. THANK YOU!!
> 
> If you want to build them locally on your machine to look at use this, starting from `./doc/`
> 
>     * Open `julia --project=..`, package manager `]` then `up`, then `dev ..`; this will make sure the package version you are building the docs for is the one you are working on. Please make sure to _NOT_ commit the Manifest that this creates!
> 
>     * Then exit julia again and from the terminal run `julia --project=.. make.jl` ; this should build the docs
> 
>     * open `./docs/build/index.html`

Thank you for such detailed instructions!! I'll follow these steps.

**Comment by cortner** [comment]
I also did a lot of cleanup of C/Rylm - when you are done let me know and I'll apply this also to your branch.

**Comment by DexuanZhou** [comment]
I've fixed the test and removed (-1)^m from real solid harmonics

**Comment by DexuanZhou** [comment]
will look at product basis and rewrite the AtomicOrbitals tomorrow

**Comment by cortner** [comment]
Thank you - and please coordinate a bit with @CheukHinHoJerry -- to ensure we aren't duplicating any work.

**Comment by cortner** [comment]
If the latest round of tests pass, then I will merge this and tag as 0.1.2

**Pull request merged**
