### PR TITLE
Add Benchmarks via PkgBenchmarks

### PR DESCRIPTION
**Pull request by tjjarvinen**
This adds Benchmarks with [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl).

To use benchmarks you can

```julia
using BenchmarkTools
using PkgBenchmark
using Polynomials4ML

bench = benchmarkpkg(Polynomials4ML)
results = bench.benchmarkgroup

# You can search with macro "@tagged"
results[@tagged "derivative"]
```

To control benchmarks e.g. number of threads

```julia
t2 = BenchmarkConfig(env = Dict("JULIA_NUM_THREADS" => 2))
bench_t2 = benchmarkpkg(Polynomials4ML, t2)
```

To save benchmarks to a file

```julia
export_markdown("results.md", bench)
```

Compare to a different branch - note you need to commit your changes (also both branches need to have same benchmarks)

```julia
# current branch to "origin/main"
j = judge(Polynomials4ML, "origin/main")
```

### Automatic benchmarks on pull requests

I added support for [BenchmarkCI.jl](https://github.com/tkf/BenchmarkCI.jl), so by adding a label "*Run Benchmarks*" on PR CI will run benchmarks and compare to main branch. (Note this only works after this PR has been merged)

There is also an option to store benchmarks in the repo, but I have commented that out.

You should also be able to add more benchmarks yourself based on the `benchmarks.jl` file.

### CODE REVIEW

**Comment by cortner** [comment]
@CheukHinHoJerry  -- when you have time, can you please take a look and familiarize yourself with this?

**Comment by CheukHinHoJerry** [comment]
Happy for this to be merged as is. Thanks.

**Comment by cortner** [comment]
@tjjarvinen -- could you maybe add the instructions to a developer documentation page in the docs? Then I'll go ahead and make the merge.

**Comment by cortner** [comment]
Is this ready now?

**Comment by tjjarvinen** [comment]
yes

**Comment by cortner** [comment]
Thank you.

**Pull request merged**
