### PR TITLE
Move ACEcore into P4ML

### PR DESCRIPTION
**Pull request by cortner**
Left todo: 

- [x] bring in the sparse basis generator
- [x] look through the ace/utils and see what we actually need and incorporate. 
- [x]  @CheukHinHoJerry  -- would you be willing to take a look at this PR and see if any functionality is now duplicated between Sparse Product and Sparse Pooled Product? 

I'm removing those two - moved to a separate issue.
- ~utility functions and unit tests for the sparse basis generator~
- ~Documentation~

### CODE REVIEW

**Comment by cortner** [comment]
CC @DexuanZhou  -- just as a heads-up that this is happening and will hopefully make all our lives easier :)

**Comment by cortner** [comment]
@CheukHinHoJerry  -- I think the product stuff. I'm not sure where it should live but probable in a separate file. Could this be part of utils? doesn't feel like it. Maybe just straight into P4ML/src.

**Comment by CheukHinHoJerry** [comment]
Re Sparse and PooledSparse Product - I think the most obvious function would be the _prod_grad and _code_prod_grad function, for other parts I think it is better just to keep it as it for now.

Re product stuffs - I don't feel like it should be in utils too, maybe just straight in P4ML/src since we don't have much functionality now. And later if we really have more ops and things become messy we can create a seperate thing like ```P4ML.func``` but I think this is not something in the near future.

**Comment by cortner** [comment]
Sounds good - maybe call it "src/staticprod.jl" - move it in there, check that tests pass, and push the changes?

**Comment by cortner** [comment]
Sorry, @CheukHinHoJerry , I was unclear what I intended ... I didn't mean to rename the type, just move the product helper functions into a separate file since it is shared functionality. I'll see if I can revert it at my end.

**Comment by CheukHinHoJerry** [comment]
> Sorry, @CheukHinHoJerry , I was unclear what I intended ... I didn't mean to rename the type, just move the product helper functions into a separate file since it is shared functionality. I'll see if I can revert it at my end.

Sorry for misunderstanding that, a point to add is that apart from _prod_grad and _code_prod_grad they also share BB_prods.

**Comment by cortner** [comment]
@CheukHinHoJerry -- I think this is ready to merge and tag. Let me know if you think anything else is still missing.

**Comment by cortner** [comment]
(I'm also tempted to register the next version with the General registry.)

**Comment by CheukHinHoJerry** [comment]
> @CheukHinHoJerry -- I think this is ready to merge and tag. Let me know if you think anything else is still missing.

I think it is good and ready to merge too.

**Pull request merged**
