### PR TITLE
Solid harmonics

### PR DESCRIPTION
**Pull request by DexuanZhou**

### CODE REVIEW

**Comment by cortner** [comment]
hi Dexuan - many thanks for getting this started. At the moment this is a huge amount of code duplication. Would it be possible to implement it as a wrapper around the spherical harmonics and just compute the scaling as a post-processing step?

**Comment by DexuanZhou** [comment]
> hi Dexuan - many thanks for getting this started. At the moment this is a huge amount of code duplication. Would it be possible to implement it as a wrapper around the spherical harmonics and just compute the scaling as a post-processing step?

Thanks for your suggestion! Sure, I'll reimplement it. 

Just to make it clear, does the "post-processing step" refer to something like this: 

function evaluate(CRlmBasis) # complex solid harmonics
       Y = evaluate(CYlmBasis): # complex spherical harmonics
       for l = 1:maxL
            Y[l] *= r^l
       end
end

but the loop for "l" has already been performed when assigning values to "Ylm", if we perform a post-processing step like this, it will loop through "l" again. I'm not sure whether it will affect the speed of the code or not.

**Comment by cortner** [comment]
Yes, something like that. We need to test the performance of course. But I suspect the overhead will be minimal and this way it will be much easier to maintain.

I also have another idea we can try but that's more complex. Remind me to discuss it?

**Comment by cortner** [comment]
Probably the "right" way to do it would be to generalize the CYlm and RYlm kernels to allow an arbitrary prefactor.

**Comment by cortner** [comment]
can I close this PR now?

**Comment by DexuanZhou** [comment]
yes, please

**Comment by cortner** [comment]
closing since it has been replaced by #13

**Pull request closed without merging**
