### PR TITLE
trainable AORlayer + some bug fixed

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
This PR mainly fixes some bugs and implements the AORlayer for trainable $\zeta$ in Gaussian basis.
The problem of matrix multiplication with `PtrArray{Hyper}` is resolved from `Octavian.jl`'s end.

Remainder on we can actually do something like this:

```julia

function (l::LuxLayer{BasisType})(X, ps, st)
     # alloc B
     evaluate!(B, basis::BasisType, X, ps)
    return B
end

evaluate!(B, basis::BasisType, X) = evaluate!(B, basis::BasisType, X, basis.ps, basis.st)

function evaluate!(B, basis::BasisType, X, ps, st)
   # this is the main evaluation code.
end
```

Maybe we can leave this PR open and use the dev branch to implement our code in `ACEpsi.jl` until we have a nice clean up with the Lux interface?

CC @cortner @DexuanZhou

### CODE REVIEW

**Comment by cortner** [comment]
What's the status of this PR?

**Comment by CheukHinHoJerry** [comment]
I think we talked about this today. I will try to do what we have discussed for trainable basis within this week. I am doing this pr together with https://github.com/ACEsuit/Polynomials4ML.jl/issues/45#issue-1765806905. Basically updates includes:

- migrating to `evaluate!(P, basis, x, zeta, tmppool)` interface and allow the use of `TempArrayCache` in lux layers.
- trainable AORbasis with pullbacks
- type instability fixes and extra tests added to make sure Zygote.gradient is calling correct overloaded pullback

**Comment by CheukHinHoJerry** [comment]
@cortner This is ready to be merged.

**Comment by cortner** [comment]
The only thing I don't really like about this PR is that it mixes a few unrelated issues - e.g. the non-allocating interface could have been treated in a separate PR. I don't think it is worth trying to separate them out now, that would be too much work. But in future, let's please try and make smaller PRs that solve discrete problems and are easier to review.

**Comment by CheukHinHoJerry** [comment]
Thank you for very review and comment. I will make sure that each PR only take care of a small and related issues in the further.

**Comment by cortner** [comment]
Does this PR need any new docs?

**Comment by cortner** [comment]
Is this a patch version?

**Comment by CheukHinHoJerry** [comment]
Re Docs:
I think I need to write a documentation for the lux layer and interfaces on pullbacks. Maybe it is also nice to have a small hierarchy diagram to explain what is `ScalarP4ML` etc...

Re patch version : 
Yes I think so.

**Comment by cortner** [comment]
I've submitted this to `General` as version 0.1.5

**Comment by CheukHinHoJerry** [comment]
Thank you very much for your review.

**Comment by cortner** [comment]
this is now registered.

**Pull request merged**
