### PR TITLE
Refactoring and Cleanup of Interface

### PR DESCRIPTION
**Pull request by cortner**
The purpose of this PR started as an experiment moving the entire P4ML package over to using Bumper and WithAlloc and removing all usage of ObjectPools. It now includes

- fully retiring OP in favour of Bumper
- cleanup of the pb and pfwd interface 
- remove all hand-written pb2 and pwfd
- cleanup of the type hierarchy 
- cleanup of allocating / non-allocating interface
- cleanup sphericart interface and retire the P4ML 3D harmonics implementations 
- some improvements to unified testing

My sense now is that the extra cost of allocations in typical ACE models will cost a moderate % of runtime, somewhere between 30-50% typically. This is more than acceptable for prototyping. For fast final models we can then hand-write the chains to get the best possible performance.

I'm unifying and finalizing the pb/pfwd interface while I do this so I can write as much shared code as possible.

### TODO 
- [x] decide on whether we support laplacians in P4ML or only the ability to use hyper-duals. It is not clear to me what is the right choice. 
- [x] bring the linear layer back (as discussed with Jerry)
- [x] make sure the sparseproduct has the functionality needed elsewhere. 
- [x] cleanup and check the lux interface
- [x] confirm the sphericart wrapper serves our purpose
- [x] rename -> `pullback!` and `pushforward!`
- [x] try and test ~unified~ second pullback via ForwardDiff 
- [x] try ~unified~ pushforward implementation via ForwardDiff
- [x] allocation tests for most embeddings and all tensors (can bring in more over time)
- [x] Extend `withalloc` to `PooledSparseProduct`

### Leave for future PRs

- [ ] complex bases seem to fail allocation tests
- [ ] improve the unified testing functions (a lot of testing functionality is duplicated throughout the `test_***` scripts
- [ ] provide literate examples how to compose manually and how to do pfwd and pb2 through such models, compare with Lux-style implementations of the same models, advantages and disadvantages
- [ ] literate example how to compute a laplacian
- [ ] update benchmark code

### CODE REVIEW

**Comment by cortner** [comment]
- [ ] The trig basis fails the allocation test

**Comment by CheukHinHoJerry** [comment]
Should we also remove anything related to `FlexArray`?

**Comment by cortner** [comment]
Yes for sure. Most of it should be gone. I just haven't reintegrated all parts of the codebase yet.

**Comment by cortner** [comment]
@CheukHinHoJerry  --  in the spirit of slimming down the package, how do we feel about making the P4ML layers actual Lux layers rather than wrapping them into Lux layers?

**Comment by CheukHinHoJerry** [comment]
I quite like the idea of having `P4ML.lux` since I can then define my structure `<:` an abstract type in P4ML and then use all the functionalities even in other packages so I prefer keeping that. But let's discuss a bit tmr? I plan to come to campus.

**Comment by cortner** [comment]
Sounds good to me.  It might actually make it easier to ensure that functinality doesn't start interfering - and we might be able to re-implement the "release" functionality.

**Comment by cortner** [comment]
I think I've now done everything I want to do for now. I propose the following: 
- @CheukHinHoJerry and @DexuanZhou , can you please take a look at the TODO lists at the top of the PR and comment if you have any concerns
- once we agreed we have a good candiate for the next minor version, I branch `main -> v0.2.x-dev` and then merge this PR into `main` i.e. it becomes the new development branch. I then register it as `0.3.0`. Any bugs, problems etc we find we can fix over the course of 0.3.x development.

**Comment by CheukHinHoJerry** [comment]
Looks good. I don't have any concern with the suggestions too.

**Comment by cortner** [comment]
@CheukHinHoJerry  -- thank you. Would you mind then taking a look at the linear layer and SparseProduct?

**Comment by cortner** [comment]
And maybe we can work together on a model building demo.

**Comment by CheukHinHoJerry** [comment]
Yes I will take a look at the linear layer first and then the sparseproduct over the weekend.

**Comment by CheukHinHoJerry** [comment]
`SparseProduct` looks fine elsewhere. I think the functionality now it provide is sufficient. I will have a final clean up now.

**Comment by cortner** [comment]
Thank you!

**Comment by cortner** [comment]
`WithAlloc.jl` is now registered in the general registry, which means we could start thinking about merging this PR and registering the next minor version? @CheukHinHoJerry , what is still missing?

**Comment by CheukHinHoJerry** [comment]
Sorry for late reply - I had some local changes on cleaning up the interface of `SparseProduct` that unifies with `PooledSparseProduct`. Just pushed them but now it is ready but I think this is now ready if the CI passes.

**Comment by CheukHinHoJerry** [comment]
CI stuck at testing `SparseSymmetricProduct`, which probably relates to #87. That doesn't happen for me previously but it suddenly occurs today. Shall we just restrict our tests to `ord > 1`?

**Comment by cortner** [comment]
Ok, I'll take a look and see if I can fix it.

**Comment by CheukHinHoJerry** [comment]
I think I see why - I will try to fix it now.

**Comment by cortner** [comment]
Thank you, Jerry!

**Comment by cortner** [comment]
So maybe my last question for @DexuanZhou and @CheukHinHoJerry  -- do you need laplacians HERE in P4ML or is it enough for you that you can use P4ML layers with Duals and HyperDuals?

**Comment by CheukHinHoJerry** [comment]
It is enough for us just to make evaluation of `Duals` and `HyperDuals` work.

**Comment by cortner** [comment]
so we are actually ready to merge this? If you confirm, I'll go ahead with it :)

**Comment by CheukHinHoJerry** [comment]
Yes please I am happy for this to be merged.

**Comment by cortner** [comment]
Everyone - thank you for your feedback and help with this PR. I've now registereed this as `v0.3.0` in the ACE registry (not in General yet since I'm having a problem with sphericart...)

**Comment by cortner** [comment]
This is now also registered in General

**Pull request merged**
