### PR TITLE
Faster Chebyshev Basis

### PR DESCRIPTION
**Pull request by cortner**
This PR implements a faster Chebyshev basis since the recursion coefficients don't have to be stored. 

@CheukHinHoJerry -- I'd be grateful if you can take a look to see if anything is missing. I will review as well before we merge it into your `frule` branch which we can hopefully then merge later this week.

### CODE REVIEW

**Comment by cortner** [comment]
@dhan-02 @vai-bhav-m  -- while we review the code and tests, would you be willing to add some documentation to record what has been implemented?

**Comment by cortner** [comment]
On a first quick check of the the code, it all looks great. I have no concerns. @CheukHinHoJerry  -- do I remember correctly that the rrules and frules for those basic polynomial embeddings are all generic and no extra work is required for that?

**Comment by CheukHinHoJerry** [comment]
The test looks fine to me too. I think this can be merged into the frule branch and it should have not much conflicts.

For rrule and frules - Yes they are the same. I can also do that easily in this merge, maybe we can also make a subclass for them like AbstractPolyEmbeddings <: AbstractPoly4MLBasis ?

**Comment by dhan-02** [comment]
> This PR implements a faster Chebyshev basis since the recursion coefficients don't have to be stored.
> 
> @CheukHinHoJerry -- I'd be grateful if you can take a look to see if anything is missing. I will review as well before we merge it into your `frule` branch which we can hopefully then merge later this week.



> @dhan-02 @vai-bhav-m -- while we review the code and tests, would you be willing to add some documentation to record what has been implemented?

Yes will do Professor....

**Comment by dhan-02** [comment]
> `chebyshev_basis` constructed from `op1d3t`

Is there any way to make it consistent with the chebyshev_basis constructed from op1d3t as far as the normalization is concerned?

**Comment by CheukHinHoJerry** [comment]
I think what you have implemented is the standard Cheb of the first kind, which is fine. But there are codes that build upon the previous basis so we should keep that. I think the best that we can do for now is to document it clearly and keep both of them.

It would be great if @cortner can suggest what we should do.

**Comment by cortner** [comment]
I agree to just document it for now. 

And I like the idea of creating a subclass for the embeddings.

**Comment by cortner** [comment]
But let's discuss that first please how to do it and how to name it.

**Comment by CheukHinHoJerry** [comment]
@dhan-02 @vai-bhav-m I have reviewed the docs and it looks good. In addition I think it is better to:

- Move the detailed description of the `ChebBasis` to backup.html (which means just move it in the comment of the code) to make the style consistent
- fix the typo ... basis with length N ... -> ... basis with length `N` ... in the comment of ChebBasis in the code
- make another warning in the comment of the code that the normalisation is different from `chebyshev_basis` from `op1d3t`

otherwise I think this is ready to merge

**Comment by cortner** [comment]
I don't think `backup.md` is used for anything, is it? I probably just dumped some Documenter code in there and then accidentally committed it?

**Comment by CheukHinHoJerry** [comment]
Sorry for confusion. What I mean is just moving the details of ChebBasis to the hyperlinks in `docstrings` (which is the same as moving it to the comment in the code). 

But for some reason, for example when I click on `CYlmBasis` it direct me to acesuit.github.io/Polynomials4ML.jl/dev/backup/#Polynomials4ML.CYlmBasis, which is in backup.html.

**Comment by cortner** [comment]
Odd then let's just delete backup.md after the merge

**Comment by CheukHinHoJerry** [comment]
I think this is ready now. I didn't clean up the comments of other files since I did that once in `frule` and I plan to do a final clean up later on.  I also added a test to make sure `ChebBasis ./ chebyshev_basis` is constant. 

The conflict is minor and should be fine.

**Comment by cortner** [comment]
ok, I'll resolve and merge. Any further cleanup in the frule branch. Any future bugfixes etc can be done anytime in further PRs.

**Pull request merged**
