### PR TITLE
WIP: add interfaces for SpheriCart ylm

### PR DESCRIPTION
**Pull request by zhanglw0521**
This PR links SpheriCart to P4ML, trying to make the evaluation of SHs and their derivatives more efficient in the resulting LuxChain.

### CODE REVIEW

**Comment by cortner** [comment]
can I review and merge?

**Comment by zhanglw0521** [comment]
Thanks for checking the status. There are still one or two small details that I need to double-check. I will get this ready to be reviewed very soon and will let you know then.

**Comment by cortner** [comment]
I would like to register sphericart in `General` first, and then we can merge and tag.

**Comment by cortner** [comment]
change of plans - I'm merging this into a new branch `lz/sphericart` so we can finalize and test the branch centrally. @zhanglw0521  -- I'll give you access of course.

**Pull request merged**
